bt_executer_node:
  ros__parameters:
    bt_xml_file: example.xml
    bt_package: drims2_homework
    plugins:
      - check_dice_face
    ros_plugins:
      - move_to_pose
      - move_to_joint
      - gripper_command
      - dice_identification
      - attach_object
      - detach_object